# GitHub Action for PHP Console Package by HungNG
name: Testing PHP Console Package by HungNG
on: [ push, pull_request ]
jobs:
    build:
        strategy:
            matrix:
                operating-system: [ 'ubuntu-latest', 'ubuntu-20.04', 'ubuntu-22.04', 'macos-latest', 'macos-11', 'macos-12' ]
                php-versions: [ '7.4', '8.0', '8.1', '8.2' ]
        runs-on: ${{ matrix.operating-system }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
            -   name: Setup PHP, with composer and extensions
                uses: shivammathur/setup-php@v2 # From https://github.com/shivammathur/setup-php
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: mbstring, intl, curl, json, openssl, iconv, sodium, mcrypt, bcmath
            -   name: Get composer cache directory
                id: composer-cache
                run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            -   name: Cache dependencies
                uses: actions/cache@v3
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Install dependencies
                run: composer install --no-dev --ignore-platform-reqs --no-progress --prefer-dist --optimize-autoloader
            #-   name: Test PHP Package Database
            #    run: php ./sample/test/test.php